#! /usr/bin/env python
# encoding: utf-8

from waflib import Context

bld.program(
    features='cxx test',
    source=['sak_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='sak_tests',
    use=['sak', 'gtest', 'test_object_xyz_lib_b'])
