#! /usr/bin/env python
# encoding: utf-8

bld.program(
    features = 'cxx test',
    source   = ['sak_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target   = 'sak_tests',
    use      = ['sak', 'gtest',
                'boost_includes', 'boost_timer', 'boost_chrono',
                'boost_system', 'test_object_xyz_lib_b'])




