#! /usr/bin/env python
# encoding: utf-8

bld.stlib(features        = 'cxx',
          source          = ['test_object_xyz_lib_a.cpp'],
          target          = 'test_object_xyz_lib_a',
          use             = ['sak'])


bld.stlib(features        = 'cxx',
          source          = ['test_object_xyz_lib_b.cpp'],
          target          = 'test_object_xyz_lib_b',
          use             = ['sak', 'test_object_xyz_lib_a'])





