#! /usr/bin/env python
# encoding: utf-8


bld.stlib(features        = 'cxx',
          source          = ['endian_buffer.cpp',
                             'duplex_buffer.cpp',
                             'platform.cpp',
                             'object_id.cpp',
                             'object_category.cpp'],
          target          = 'sak',
          cxxflags        = bld.toolchain_cxx_flags(),
          export_includes = '..',
          use             = ['boost_includes'])
