#! /usr/bin/env python
# encoding: utf-8


bld.stlib(features        = 'cxx',
          source          = bld.path.ant_glob('**/*.cpp'),
          target          = 'sak',
          cxxflags        = bld.toolchain_cxx_flags(),
          export_includes = '..',
          use             = ['boost_includes'])
